/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/license/': RouteRecordInfo<'/license/', '/license', Record<never, never>, Record<never, never>>,
    '/license/[licenseId]/': RouteRecordInfo<'/license/[licenseId]/', '/license/:licenseId', { licenseId: ParamValue<true> }, { licenseId: ParamValue<false> }>,
    '/license/[licenseId]/project/': RouteRecordInfo<'/license/[licenseId]/project/', '/license/:licenseId/project', { licenseId: ParamValue<true> }, { licenseId: ParamValue<false> }>,
    '/license/[licenseId]/project/[projectId]': RouteRecordInfo<'/license/[licenseId]/project/[projectId]', '/license/:licenseId/project/:projectId', { licenseId: ParamValue<true>, projectId: ParamValue<true> }, { licenseId: ParamValue<false>, projectId: ParamValue<false> }>,
  }
}
